### PR TITLE
Sync JSON-YAML Recipe Example

### PR DESCRIPTION
**Pull request by gt1485a**
*Issue #, if available:*

*Description of changes:*
the last lifecycle tag in the yaml version doesn't match the json version. Updated yaml to match json

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by FThompsonAWS** [comment]
Thank you for sharing that the JSON and YAML recipes don't match in the last example. The JSON example should use "Install" like the YAML example. I see that you closed the PR, but we'll go ahead and make this change so the examples are consistent.

**Comment by gt1485a** [comment]
I closed the pr as the recipe documentation doesn't have "Start" as a valid
keyword. Startup and Run seem to be valid though. Since you are intimate
with the code I'll let you decide where to go from here.😁

Ryan

**Comment by gt1485a** [comment]
Re read your email, I'm understanding it now.
Thanks....

**Comment by FThompsonAWS** [comment]
I've updated the documentation website and the markdown in this repository to reflect using `Install` in the JSON example. Thanks for bringing this to our attention!

**Pull request closed without merging**
